// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// 视频/项目基础信息。对应 gyroflow_ffi.h 的 GyroflowVideoInfo。
///
/// Generated class from Pigeon that represents data sent in messages.
struct VideoInfo {
  var width: Int64? = nil
  var height: Int64? = nil
  var outputWidth: Int64? = nil
  var outputHeight: Int64? = nil
  var fps: Double? = nil
  var durationS: Double? = nil
  var frameCount: Int64? = nil
  var videoCodec: String? = nil
  var pixelFormat: String? = nil
  var audioCodec: String? = nil
  var audioSampleRate: Int64? = nil
  var rotationDeg: Int64? = nil
  var videoBitrate: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VideoInfo? {
    let width: Int64? = nilOrValue(pigeonVar_list[0])
    let height: Int64? = nilOrValue(pigeonVar_list[1])
    let outputWidth: Int64? = nilOrValue(pigeonVar_list[2])
    let outputHeight: Int64? = nilOrValue(pigeonVar_list[3])
    let fps: Double? = nilOrValue(pigeonVar_list[4])
    let durationS: Double? = nilOrValue(pigeonVar_list[5])
    let frameCount: Int64? = nilOrValue(pigeonVar_list[6])
    let videoCodec: String? = nilOrValue(pigeonVar_list[7])
    let pixelFormat: String? = nilOrValue(pigeonVar_list[8])
    let audioCodec: String? = nilOrValue(pigeonVar_list[9])
    let audioSampleRate: Int64? = nilOrValue(pigeonVar_list[10])
    let rotationDeg: Int64? = nilOrValue(pigeonVar_list[11])
    let videoBitrate: Int64? = nilOrValue(pigeonVar_list[12])

    return VideoInfo(
      width: width,
      height: height,
      outputWidth: outputWidth,
      outputHeight: outputHeight,
      fps: fps,
      durationS: durationS,
      frameCount: frameCount,
      videoCodec: videoCodec,
      pixelFormat: pixelFormat,
      audioCodec: audioCodec,
      audioSampleRate: audioSampleRate,
      rotationDeg: rotationDeg,
      videoBitrate: videoBitrate
    )
  }
  func toList() -> [Any?] {
    return [
      width,
      height,
      outputWidth,
      outputHeight,
      fps,
      durationS,
      frameCount,
      videoCodec,
      pixelFormat,
      audioCodec,
      audioSampleRate,
      rotationDeg,
      videoBitrate,
    ]
  }
}

/// recompute 后的只读输出(供 UI 显示最大修正角 / zoom% = 100/minFov)。
///
/// Generated class from Pigeon that represents data sent in messages.
struct StabInfo {
  var maxAnglePitch: Double? = nil
  var maxAngleYaw: Double? = nil
  var maxAngleRoll: Double? = nil
  var minFov: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> StabInfo? {
    let maxAnglePitch: Double? = nilOrValue(pigeonVar_list[0])
    let maxAngleYaw: Double? = nilOrValue(pigeonVar_list[1])
    let maxAngleRoll: Double? = nilOrValue(pigeonVar_list[2])
    let minFov: Double? = nilOrValue(pigeonVar_list[3])

    return StabInfo(
      maxAnglePitch: maxAnglePitch,
      maxAngleYaw: maxAngleYaw,
      maxAngleRoll: maxAngleRoll,
      minFov: minFov
    )
  }
  func toList() -> [Any?] {
    return [
      maxAnglePitch,
      maxAngleYaw,
      maxAngleRoll,
      minFov,
    ]
  }
}

/// 预览纹理信息(阶段1)。创建预览纹理后返回 textureId 与画面尺寸。
///
/// Generated class from Pigeon that represents data sent in messages.
struct PreviewInfo {
  var textureId: Int64? = nil
  var width: Int64? = nil
  var height: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PreviewInfo? {
    let textureId: Int64? = nilOrValue(pigeonVar_list[0])
    let width: Int64? = nilOrValue(pigeonVar_list[1])
    let height: Int64? = nilOrValue(pigeonVar_list[2])

    return PreviewInfo(
      textureId: textureId,
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      textureId,
      width,
      height,
    ]
  }
}

/// 导出请求(对齐旧原生 runExportFromURL 入参):源视频 + 输出位置 + 编码参数 + 输出尺寸。
///
/// Generated class from Pigeon that represents data sent in messages.
struct ExportRequest {
  var srcUri: String? = nil
  var outputUri: String? = nil
  var fileName: String? = nil
  var codecIndex: Int64? = nil
  var bitrateMbps: Int64? = nil
  var exportAudio: Bool? = nil
  var width: Int64? = nil
  var height: Int64? = nil
  var trimStartUs: Int64? = nil
  var trimEndUs: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ExportRequest? {
    let srcUri: String? = nilOrValue(pigeonVar_list[0])
    let outputUri: String? = nilOrValue(pigeonVar_list[1])
    let fileName: String? = nilOrValue(pigeonVar_list[2])
    let codecIndex: Int64? = nilOrValue(pigeonVar_list[3])
    let bitrateMbps: Int64? = nilOrValue(pigeonVar_list[4])
    let exportAudio: Bool? = nilOrValue(pigeonVar_list[5])
    let width: Int64? = nilOrValue(pigeonVar_list[6])
    let height: Int64? = nilOrValue(pigeonVar_list[7])
    let trimStartUs: Int64? = nilOrValue(pigeonVar_list[8])
    let trimEndUs: Int64? = nilOrValue(pigeonVar_list[9])

    return ExportRequest(
      srcUri: srcUri,
      outputUri: outputUri,
      fileName: fileName,
      codecIndex: codecIndex,
      bitrateMbps: bitrateMbps,
      exportAudio: exportAudio,
      width: width,
      height: height,
      trimStartUs: trimStartUs,
      trimEndUs: trimEndUs
    )
  }
  func toList() -> [Any?] {
    return [
      srcUri,
      outputUri,
      fileName,
      codecIndex,
      bitrateMbps,
      exportAudio,
      width,
      height,
      trimStartUs,
      trimEndUs,
    ]
  }
}

private class EngineApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return VideoInfo.fromList(self.readValue() as! [Any?])
    case 130:
      return StabInfo.fromList(self.readValue() as! [Any?])
    case 131:
      return PreviewInfo.fromList(self.readValue() as! [Any?])
    case 132:
      return ExportRequest.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class EngineApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? VideoInfo {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? StabInfo {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? PreviewInfo {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? ExportRequest {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class EngineApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return EngineApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return EngineApiPigeonCodecWriter(data: data)
  }
}

class EngineApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = EngineApiPigeonCodec(readerWriter: EngineApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol EngineApi {
  func createStabilizer() throws
  func freeStabilizer() throws
  func openVideo(uriOrPath: String, completion: @escaping (Result<VideoInfo, Error>) -> Void)
  func setStabEnabled(enabled: Bool) throws
  func setSmoothingMethod(index: Int64) throws
  func setSmoothingParam(name: String, value: Double) throws
  /// 对齐 gyroflow_set_horizon_lock 全 9 参。
  /// (安卓 nativeSetHorizonLock 目前 2 参,impl 内补齐其余默认。)
  func setHorizonLock(lockPercent: Double, rollDeg: Double, lockPitch: Bool, pitchDeg: Double, automaticLock: Bool, turnThreshold: Double, turnSmoothingMs: Double, turnMultiplier: Double, tiltAccelLimit: Double) throws
  func setAdaptiveZoom(windowSeconds: Double) throws
  func setMaxZoom(percent: Double, iterations: Int64) throws
  func setZoomingMethod(index: Int64) throws
  func setLensCorrection(amount: Double) throws
  func setFov(fov: Double) throws
  func setFrameReadoutTime(ms: Double) throws
  func setFrameReadoutDirection(dir: Int64) throws
  func setVideoSpeed(speed: Double, affectsSmoothing: Bool, affectsZooming: Bool, affectsZoomingLimit: Bool) throws
  func setAdditionalRotation(pitchDeg: Double, yawDeg: Double, rollDeg: Double) throws
  func setBackgroundColor(r: Double, g: Double, b: Double, a: Double) throws
  func setBackgroundMode(mode: Int64) throws
  func setShowSafeArea(show: Bool) throws
  func setShowDetectedFeatures(show: Bool) throws
  func setShowOpticalFlow(show: Bool) throws
  func setPreviewResolution(targetHeight: Int64) throws
  func setOutputSize(width: Int64, height: Int64) throws
  func setOutputSizeExact(width: Int64, height: Int64) throws
  /// 查询本机该编码格式硬件编码器的最大可导出分辨率 [maxW, maxH]。
  /// 导出面板据此「按当前机型 + 编码格式」过滤输出大小预设(看得到的尺寸就一定能导出:
  /// 三星支持 8K 就显示到 8K,华为只到 4K 就只显示到 4K)。codecIndex: 0=H.264 1=HEVC。
  /// 仅只读查询能力,不创建编码器、不影响引擎/导出。查不到→返回编码标准规格上限兜底。
  func encoderMaxSize(codecIndex: Int64) throws -> [Int64]
  func setGyroOffset(offsetMs: Double) throws
  func setImuLpf(hz: Double) throws
  func setImuMedian(samples: Int64) throws
  func setImuRotation(pitchDeg: Double, rollDeg: Double, yawDeg: Double) throws
  func setImuBias(x: Double, y: Double, z: Double) throws
  func setImuOrientation(orientation: String) throws
  func setIntegrationMethod(index: Int64) throws
  func setFrameOffset(frames: Int64) throws
  func lensSearch(query: String) throws -> String
  func loadLens(uriOrIdOrJson: String) throws -> String
  func getLensInfoFull() throws -> String
  /// 按当前已识别相机身份(camera_id)从内置库自动加载镜头档案。用于「相机身份在外挂
  /// .gcsv 里、视频本身无 telemetry」的机型(如 RunCam6):加载 gcsv 后调用。
  /// 返回 gyroflow_autoload_lens_for_camera 的 rc:0=已加载;-2=无可匹配/已有档案;-1=错。
  /// (安卓 nativeLoadGyro 已在加载时内部自动配镜头,该方法在安卓为 no-op。)
  func autoloadLensForCamera() throws -> Int64
  func loadGyro(uriOrPath: String, loadAllMetadata: Bool) throws -> String
  func folderAccessGranted(folderUrl: String) throws
  /// 阻塞重算(放后台队列执行)+ 返回 max angles / min fov。
  /// 完成后另经 EngineEvents.onRecomputeFinished 通知一次,便于 UI 统一刷新。
  func recomputeBlocking(completion: @escaping (Result<StabInfo, Error>) -> Void)
  func getVideoMetadata() throws -> String
  /// 运动数据当前状态 JSON(供「输入」面板回显):
  /// {"imu_orientation":"ZyX","has_quaternions":bool,"integration_method":int,
  ///  "lpf":double,"median":int,"rotation":[p,r,y],"bias":[x,y,z]}
  /// 安卓 nativeGetGyroInfo 全字段;iOS 用 get_imu_orientation + has_quaternions 拼核心字段。
  func getGyroInfo() throws -> String
  func gyroTimeline(count: Int64) throws -> [Double]
  func quaternionTimeline(count: Int64) throws -> [Double]
  func quatsAtTimestamp(timestampUs: Int64) throws -> [Double]
  func getFovAtTimestamp(timestampUs: Int64) throws -> Double
  func autosyncStart(uriOrPath: String, initialOffsetMs: Double, searchSizeSec: Double, maxSyncPoints: Int64, everyNthFrame: Int64, timePerSyncpointSec: Double, ofMethod: Int64, poseMethod: Int64, offsetMethod: Int64, calcInitialFast: Bool, checkNegativeInitialOffset: Bool, autoSyncPoints: Bool) throws
  func autosyncCancel() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class EngineApiSetup {
  static var codec: FlutterStandardMessageCodec { EngineApiPigeonCodec.shared }
  /// Sets up an instance of `EngineApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: EngineApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let createStabilizerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.createStabilizer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createStabilizerChannel.setMessageHandler { _, reply in
        do {
          try api.createStabilizer()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      createStabilizerChannel.setMessageHandler(nil)
    }
    let freeStabilizerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.freeStabilizer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      freeStabilizerChannel.setMessageHandler { _, reply in
        do {
          try api.freeStabilizer()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      freeStabilizerChannel.setMessageHandler(nil)
    }
    let openVideoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.openVideo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openVideoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let uriOrPathArg = args[0] as! String
        api.openVideo(uriOrPath: uriOrPathArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      openVideoChannel.setMessageHandler(nil)
    }
    let setStabEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.setStabEnabled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setStabEnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        do {
          try api.setStabEnabled(enabled: enabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setStabEnabledChannel.setMessageHandler(nil)
    }
    let setSmoothingMethodChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.setSmoothingMethod\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setSmoothingMethodChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let indexArg = args[0] as! Int64
        do {
          try api.setSmoothingMethod(index: indexArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setSmoothingMethodChannel.setMessageHandler(nil)
    }
    let setSmoothingParamChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.setSmoothingParam\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setSmoothingParamChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nameArg = args[0] as! String
        let valueArg = args[1] as! Double
        do {
          try api.setSmoothingParam(name: nameArg, value: valueArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setSmoothingParamChannel.setMessageHandler(nil)
    }
    /// 对齐 gyroflow_set_horizon_lock 全 9 参。
    /// (安卓 nativeSetHorizonLock 目前 2 参,impl 内补齐其余默认。)
    let setHorizonLockChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.setHorizonLock\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setHorizonLockChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let lockPercentArg = args[0] as! Double
        let rollDegArg = args[1] as! Double
        let lockPitchArg = args[2] as! Bool
        let pitchDegArg = args[3] as! Double
        let automaticLockArg = args[4] as! Bool
        let turnThresholdArg = args[5] as! Double
        let turnSmoothingMsArg = args[6] as! Double
        let turnMultiplierArg = args[7] as! Double
        let tiltAccelLimitArg = args[8] as! Double
        do {
          try api.setHorizonLock(lockPercent: lockPercentArg, rollDeg: rollDegArg, lockPitch: lockPitchArg, pitchDeg: pitchDegArg, automaticLock: automaticLockArg, turnThreshold: turnThresholdArg, turnSmoothingMs: turnSmoothingMsArg, turnMultiplier: turnMultiplierArg, tiltAccelLimit: tiltAccelLimitArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setHorizonLockChannel.setMessageHandler(nil)
    }
    let setAdaptiveZoomChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.setAdaptiveZoom\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setAdaptiveZoomChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let windowSecondsArg = args[0] as! Double
        do {
          try api.setAdaptiveZoom(windowSeconds: windowSecondsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setAdaptiveZoomChannel.setMessageHandler(nil)
    }
    let setMaxZoomChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.setMaxZoom\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setMaxZoomChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let percentArg = args[0] as! Double
        let iterationsArg = args[1] as! Int64
        do {
          try api.setMaxZoom(percent: percentArg, iterations: iterationsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setMaxZoomChannel.setMessageHandler(nil)
    }
    let setZoomingMethodChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.setZoomingMethod\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setZoomingMethodChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let indexArg = args[0] as! Int64
        do {
          try api.setZoomingMethod(index: indexArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setZoomingMethodChannel.setMessageHandler(nil)
    }
    let setLensCorrectionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.setLensCorrection\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setLensCorrectionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let amountArg = args[0] as! Double
        do {
          try api.setLensCorrection(amount: amountArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setLensCorrectionChannel.setMessageHandler(nil)
    }
    let setFovChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.setFov\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setFovChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let fovArg = args[0] as! Double
        do {
          try api.setFov(fov: fovArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setFovChannel.setMessageHandler(nil)
    }
    let setFrameReadoutTimeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.setFrameReadoutTime\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setFrameReadoutTimeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let msArg = args[0] as! Double
        do {
          try api.setFrameReadoutTime(ms: msArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setFrameReadoutTimeChannel.setMessageHandler(nil)
    }
    let setFrameReadoutDirectionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.setFrameReadoutDirection\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setFrameReadoutDirectionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let dirArg = args[0] as! Int64
        do {
          try api.setFrameReadoutDirection(dir: dirArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setFrameReadoutDirectionChannel.setMessageHandler(nil)
    }
    let setVideoSpeedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.setVideoSpeed\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setVideoSpeedChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let speedArg = args[0] as! Double
        let affectsSmoothingArg = args[1] as! Bool
        let affectsZoomingArg = args[2] as! Bool
        let affectsZoomingLimitArg = args[3] as! Bool
        do {
          try api.setVideoSpeed(speed: speedArg, affectsSmoothing: affectsSmoothingArg, affectsZooming: affectsZoomingArg, affectsZoomingLimit: affectsZoomingLimitArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setVideoSpeedChannel.setMessageHandler(nil)
    }
    let setAdditionalRotationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.setAdditionalRotation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setAdditionalRotationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pitchDegArg = args[0] as! Double
        let yawDegArg = args[1] as! Double
        let rollDegArg = args[2] as! Double
        do {
          try api.setAdditionalRotation(pitchDeg: pitchDegArg, yawDeg: yawDegArg, rollDeg: rollDegArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setAdditionalRotationChannel.setMessageHandler(nil)
    }
    let setBackgroundColorChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.setBackgroundColor\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setBackgroundColorChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let rArg = args[0] as! Double
        let gArg = args[1] as! Double
        let bArg = args[2] as! Double
        let aArg = args[3] as! Double
        do {
          try api.setBackgroundColor(r: rArg, g: gArg, b: bArg, a: aArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setBackgroundColorChannel.setMessageHandler(nil)
    }
    let setBackgroundModeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.setBackgroundMode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setBackgroundModeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let modeArg = args[0] as! Int64
        do {
          try api.setBackgroundMode(mode: modeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setBackgroundModeChannel.setMessageHandler(nil)
    }
    let setShowSafeAreaChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.setShowSafeArea\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setShowSafeAreaChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let showArg = args[0] as! Bool
        do {
          try api.setShowSafeArea(show: showArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setShowSafeAreaChannel.setMessageHandler(nil)
    }
    let setShowDetectedFeaturesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.setShowDetectedFeatures\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setShowDetectedFeaturesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let showArg = args[0] as! Bool
        do {
          try api.setShowDetectedFeatures(show: showArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setShowDetectedFeaturesChannel.setMessageHandler(nil)
    }
    let setShowOpticalFlowChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.setShowOpticalFlow\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setShowOpticalFlowChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let showArg = args[0] as! Bool
        do {
          try api.setShowOpticalFlow(show: showArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setShowOpticalFlowChannel.setMessageHandler(nil)
    }
    let setPreviewResolutionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.setPreviewResolution\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setPreviewResolutionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let targetHeightArg = args[0] as! Int64
        do {
          try api.setPreviewResolution(targetHeight: targetHeightArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setPreviewResolutionChannel.setMessageHandler(nil)
    }
    let setOutputSizeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.setOutputSize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setOutputSizeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let widthArg = args[0] as! Int64
        let heightArg = args[1] as! Int64
        do {
          try api.setOutputSize(width: widthArg, height: heightArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setOutputSizeChannel.setMessageHandler(nil)
    }
    let setOutputSizeExactChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.setOutputSizeExact\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setOutputSizeExactChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let widthArg = args[0] as! Int64
        let heightArg = args[1] as! Int64
        do {
          try api.setOutputSizeExact(width: widthArg, height: heightArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setOutputSizeExactChannel.setMessageHandler(nil)
    }
    /// 查询本机该编码格式硬件编码器的最大可导出分辨率 [maxW, maxH]。
    /// 导出面板据此「按当前机型 + 编码格式」过滤输出大小预设(看得到的尺寸就一定能导出:
    /// 三星支持 8K 就显示到 8K,华为只到 4K 就只显示到 4K)。codecIndex: 0=H.264 1=HEVC。
    /// 仅只读查询能力,不创建编码器、不影响引擎/导出。查不到→返回编码标准规格上限兜底。
    let encoderMaxSizeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.encoderMaxSize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      encoderMaxSizeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let codecIndexArg = args[0] as! Int64
        do {
          let result = try api.encoderMaxSize(codecIndex: codecIndexArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      encoderMaxSizeChannel.setMessageHandler(nil)
    }
    let setGyroOffsetChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.setGyroOffset\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setGyroOffsetChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let offsetMsArg = args[0] as! Double
        do {
          try api.setGyroOffset(offsetMs: offsetMsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setGyroOffsetChannel.setMessageHandler(nil)
    }
    let setImuLpfChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.setImuLpf\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setImuLpfChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let hzArg = args[0] as! Double
        do {
          try api.setImuLpf(hz: hzArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setImuLpfChannel.setMessageHandler(nil)
    }
    let setImuMedianChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.setImuMedian\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setImuMedianChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let samplesArg = args[0] as! Int64
        do {
          try api.setImuMedian(samples: samplesArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setImuMedianChannel.setMessageHandler(nil)
    }
    let setImuRotationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.setImuRotation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setImuRotationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pitchDegArg = args[0] as! Double
        let rollDegArg = args[1] as! Double
        let yawDegArg = args[2] as! Double
        do {
          try api.setImuRotation(pitchDeg: pitchDegArg, rollDeg: rollDegArg, yawDeg: yawDegArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setImuRotationChannel.setMessageHandler(nil)
    }
    let setImuBiasChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.setImuBias\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setImuBiasChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let xArg = args[0] as! Double
        let yArg = args[1] as! Double
        let zArg = args[2] as! Double
        do {
          try api.setImuBias(x: xArg, y: yArg, z: zArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setImuBiasChannel.setMessageHandler(nil)
    }
    let setImuOrientationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.setImuOrientation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setImuOrientationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let orientationArg = args[0] as! String
        do {
          try api.setImuOrientation(orientation: orientationArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setImuOrientationChannel.setMessageHandler(nil)
    }
    let setIntegrationMethodChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.setIntegrationMethod\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setIntegrationMethodChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let indexArg = args[0] as! Int64
        do {
          try api.setIntegrationMethod(index: indexArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setIntegrationMethodChannel.setMessageHandler(nil)
    }
    let setFrameOffsetChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.setFrameOffset\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setFrameOffsetChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let framesArg = args[0] as! Int64
        do {
          try api.setFrameOffset(frames: framesArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setFrameOffsetChannel.setMessageHandler(nil)
    }
    let lensSearchChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.lensSearch\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      lensSearchChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let queryArg = args[0] as! String
        do {
          let result = try api.lensSearch(query: queryArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      lensSearchChannel.setMessageHandler(nil)
    }
    let loadLensChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.loadLens\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadLensChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let uriOrIdOrJsonArg = args[0] as! String
        do {
          let result = try api.loadLens(uriOrIdOrJson: uriOrIdOrJsonArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      loadLensChannel.setMessageHandler(nil)
    }
    let getLensInfoFullChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.getLensInfoFull\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getLensInfoFullChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getLensInfoFull()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getLensInfoFullChannel.setMessageHandler(nil)
    }
    /// 按当前已识别相机身份(camera_id)从内置库自动加载镜头档案。用于「相机身份在外挂
    /// .gcsv 里、视频本身无 telemetry」的机型(如 RunCam6):加载 gcsv 后调用。
    /// 返回 gyroflow_autoload_lens_for_camera 的 rc:0=已加载;-2=无可匹配/已有档案;-1=错。
    /// (安卓 nativeLoadGyro 已在加载时内部自动配镜头,该方法在安卓为 no-op。)
    let autoloadLensForCameraChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.autoloadLensForCamera\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      autoloadLensForCameraChannel.setMessageHandler { _, reply in
        do {
          let result = try api.autoloadLensForCamera()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      autoloadLensForCameraChannel.setMessageHandler(nil)
    }
    let loadGyroChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.loadGyro\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadGyroChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let uriOrPathArg = args[0] as! String
        let loadAllMetadataArg = args[1] as! Bool
        do {
          let result = try api.loadGyro(uriOrPath: uriOrPathArg, loadAllMetadata: loadAllMetadataArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      loadGyroChannel.setMessageHandler(nil)
    }
    let folderAccessGrantedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.folderAccessGranted\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      folderAccessGrantedChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let folderUrlArg = args[0] as! String
        do {
          try api.folderAccessGranted(folderUrl: folderUrlArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      folderAccessGrantedChannel.setMessageHandler(nil)
    }
    /// 阻塞重算(放后台队列执行)+ 返回 max angles / min fov。
    /// 完成后另经 EngineEvents.onRecomputeFinished 通知一次,便于 UI 统一刷新。
    let recomputeBlockingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.recomputeBlocking\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      recomputeBlockingChannel.setMessageHandler { _, reply in
        api.recomputeBlocking { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      recomputeBlockingChannel.setMessageHandler(nil)
    }
    let getVideoMetadataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.getVideoMetadata\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getVideoMetadataChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getVideoMetadata()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getVideoMetadataChannel.setMessageHandler(nil)
    }
    /// 运动数据当前状态 JSON(供「输入」面板回显):
    /// {"imu_orientation":"ZyX","has_quaternions":bool,"integration_method":int,
    ///  "lpf":double,"median":int,"rotation":[p,r,y],"bias":[x,y,z]}
    /// 安卓 nativeGetGyroInfo 全字段;iOS 用 get_imu_orientation + has_quaternions 拼核心字段。
    let getGyroInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.getGyroInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getGyroInfoChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getGyroInfo()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getGyroInfoChannel.setMessageHandler(nil)
    }
    let gyroTimelineChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.gyroTimeline\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      gyroTimelineChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let countArg = args[0] as! Int64
        do {
          let result = try api.gyroTimeline(count: countArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      gyroTimelineChannel.setMessageHandler(nil)
    }
    let quaternionTimelineChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.quaternionTimeline\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      quaternionTimelineChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let countArg = args[0] as! Int64
        do {
          let result = try api.quaternionTimeline(count: countArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      quaternionTimelineChannel.setMessageHandler(nil)
    }
    let quatsAtTimestampChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.quatsAtTimestamp\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      quatsAtTimestampChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let timestampUsArg = args[0] as! Int64
        do {
          let result = try api.quatsAtTimestamp(timestampUs: timestampUsArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      quatsAtTimestampChannel.setMessageHandler(nil)
    }
    let getFovAtTimestampChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.getFovAtTimestamp\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getFovAtTimestampChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let timestampUsArg = args[0] as! Int64
        do {
          let result = try api.getFovAtTimestamp(timestampUs: timestampUsArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getFovAtTimestampChannel.setMessageHandler(nil)
    }
    let autosyncStartChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.autosyncStart\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      autosyncStartChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let uriOrPathArg = args[0] as! String
        let initialOffsetMsArg = args[1] as! Double
        let searchSizeSecArg = args[2] as! Double
        let maxSyncPointsArg = args[3] as! Int64
        let everyNthFrameArg = args[4] as! Int64
        let timePerSyncpointSecArg = args[5] as! Double
        let ofMethodArg = args[6] as! Int64
        let poseMethodArg = args[7] as! Int64
        let offsetMethodArg = args[8] as! Int64
        let calcInitialFastArg = args[9] as! Bool
        let checkNegativeInitialOffsetArg = args[10] as! Bool
        let autoSyncPointsArg = args[11] as! Bool
        do {
          try api.autosyncStart(uriOrPath: uriOrPathArg, initialOffsetMs: initialOffsetMsArg, searchSizeSec: searchSizeSecArg, maxSyncPoints: maxSyncPointsArg, everyNthFrame: everyNthFrameArg, timePerSyncpointSec: timePerSyncpointSecArg, ofMethod: ofMethodArg, poseMethod: poseMethodArg, offsetMethod: offsetMethodArg, calcInitialFast: calcInitialFastArg, checkNegativeInitialOffset: checkNegativeInitialOffsetArg, autoSyncPoints: autoSyncPointsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      autosyncStartChannel.setMessageHandler(nil)
    }
    let autosyncCancelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.EngineApi.autosyncCancel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      autosyncCancelChannel.setMessageHandler { _, reply in
        do {
          try api.autosyncCancel()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      autosyncCancelChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol EngineEventsProtocol {
  /// recompute_blocking 在后台完成后,回主线程通知(刷 max angles / minFov)。
  func onRecomputeFinished(info infoArg: StabInfo, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// autosync 进度(ready/total 对齐官方 on_progress)。
  func onAutosyncProgress(progress progressArg: Double, ready readyArg: Int64, total totalArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// autosync 结束。medianOffsetMs 仅显示用;syncPoints 交错 [mid_ms, off_ms, ...]。
  /// iOS 出参 / 安卓 JSON 在各端 impl 内归一成本回调。
  func onAutosyncFinished(medianOffsetMs medianOffsetMsArg: Double, syncPoints syncPointsArg: [Double], ok okArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// 导出进度(渲染线程回调,impl 内切回主线程再发)。
  func onExportProgress(progress progressArg: Double, frame frameArg: Int64, total totalArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// 播放推进:供 Flutter HUD 显示时间码 / zoom%(阶段 3 用)。
  func onPlaybackTick(timestampUs timestampUsArg: Int64, fov fovArg: Double, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class EngineEvents: EngineEventsProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: EngineApiPigeonCodec {
    return EngineApiPigeonCodec.shared
  }
  /// recompute_blocking 在后台完成后,回主线程通知(刷 max angles / minFov)。
  func onRecomputeFinished(info infoArg: StabInfo, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.runcam_gf.EngineEvents.onRecomputeFinished\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([infoArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  /// autosync 进度(ready/total 对齐官方 on_progress)。
  func onAutosyncProgress(progress progressArg: Double, ready readyArg: Int64, total totalArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.runcam_gf.EngineEvents.onAutosyncProgress\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([progressArg, readyArg, totalArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  /// autosync 结束。medianOffsetMs 仅显示用;syncPoints 交错 [mid_ms, off_ms, ...]。
  /// iOS 出参 / 安卓 JSON 在各端 impl 内归一成本回调。
  func onAutosyncFinished(medianOffsetMs medianOffsetMsArg: Double, syncPoints syncPointsArg: [Double], ok okArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.runcam_gf.EngineEvents.onAutosyncFinished\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([medianOffsetMsArg, syncPointsArg, okArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  /// 导出进度(渲染线程回调,impl 内切回主线程再发)。
  func onExportProgress(progress progressArg: Double, frame frameArg: Int64, total totalArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.runcam_gf.EngineEvents.onExportProgress\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([progressArg, frameArg, totalArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  /// 播放推进:供 Flutter HUD 显示时间码 / zoom%(阶段 3 用)。
  func onPlaybackTick(timestampUs timestampUsArg: Int64, fov fovArg: Double, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.runcam_gf.EngineEvents.onPlaybackTick\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([timestampUsArg, fovArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PreviewApi {
  /// 创建外接预览纹理。建解码器+CVPB 池+注册纹理,返回 textureId 与画面尺寸
  /// (阶段1:iOS FlutterTexture / 安卓 SurfaceProducer)。
  func createPreviewTexture(uriOrPath: String) throws -> PreviewInfo
  func disposePreviewTexture(textureId: Int64) throws
  func play() throws
  func pause() throws
  func seekTo(timestampUs: Int64) throws
  /// 暂停态按需重渲当前帧:参数改动后 recompute 完,主动刷新一次预览
  /// (播放时渲染循环已连续刷新,无需调用)。
  func renderOnce() throws
  /// 取并清零"自上次调用以来 copyPixelBuffer 被调次数"= Flutter 实际合成/上屏该
  /// 纹理的帧数。每秒调一次即得真实合成 FPS(Dart 的 addTimingsCallback 只统计框架帧、
  /// 看不到外部纹理合成,故须在原生侧计数)。
  func takeCompositedFrameCount() throws -> Int64
  /// 导出模式:开启后逐帧只渲输出供回读、不上屏(对齐 nativeSetExportMode)。
  func setExportMode(on: Bool) throws
  /// 开始导出(对齐旧原生 runExportFromURL):复用共享 stabilizer 逐帧
  /// 解码→process_frame→编码写文件,进度经 EngineEvents.onExportProgress 回报。
  /// 返回空串=成功;非空=错误信息(取消时返回「已取消」)。
  func startExport(req: ExportRequest, completion: @escaping (Result<String, Error>) -> Void)
  /// 取消进行中的导出(置标志,导出循环下一帧自停)。
  func cancelExport() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PreviewApiSetup {
  static var codec: FlutterStandardMessageCodec { EngineApiPigeonCodec.shared }
  /// Sets up an instance of `PreviewApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PreviewApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// 创建外接预览纹理。建解码器+CVPB 池+注册纹理,返回 textureId 与画面尺寸
    /// (阶段1:iOS FlutterTexture / 安卓 SurfaceProducer)。
    let createPreviewTextureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.PreviewApi.createPreviewTexture\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createPreviewTextureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let uriOrPathArg = args[0] as! String
        do {
          let result = try api.createPreviewTexture(uriOrPath: uriOrPathArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      createPreviewTextureChannel.setMessageHandler(nil)
    }
    let disposePreviewTextureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.PreviewApi.disposePreviewTexture\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposePreviewTextureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let textureIdArg = args[0] as! Int64
        do {
          try api.disposePreviewTexture(textureId: textureIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disposePreviewTextureChannel.setMessageHandler(nil)
    }
    let playChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.PreviewApi.play\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      playChannel.setMessageHandler { _, reply in
        do {
          try api.play()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      playChannel.setMessageHandler(nil)
    }
    let pauseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.PreviewApi.pause\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pauseChannel.setMessageHandler { _, reply in
        do {
          try api.pause()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pauseChannel.setMessageHandler(nil)
    }
    let seekToChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.PreviewApi.seekTo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      seekToChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let timestampUsArg = args[0] as! Int64
        do {
          try api.seekTo(timestampUs: timestampUsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      seekToChannel.setMessageHandler(nil)
    }
    /// 暂停态按需重渲当前帧:参数改动后 recompute 完,主动刷新一次预览
    /// (播放时渲染循环已连续刷新,无需调用)。
    let renderOnceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.PreviewApi.renderOnce\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      renderOnceChannel.setMessageHandler { _, reply in
        do {
          try api.renderOnce()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      renderOnceChannel.setMessageHandler(nil)
    }
    /// 取并清零"自上次调用以来 copyPixelBuffer 被调次数"= Flutter 实际合成/上屏该
    /// 纹理的帧数。每秒调一次即得真实合成 FPS(Dart 的 addTimingsCallback 只统计框架帧、
    /// 看不到外部纹理合成,故须在原生侧计数)。
    let takeCompositedFrameCountChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.PreviewApi.takeCompositedFrameCount\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      takeCompositedFrameCountChannel.setMessageHandler { _, reply in
        do {
          let result = try api.takeCompositedFrameCount()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      takeCompositedFrameCountChannel.setMessageHandler(nil)
    }
    /// 导出模式:开启后逐帧只渲输出供回读、不上屏(对齐 nativeSetExportMode)。
    let setExportModeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.PreviewApi.setExportMode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setExportModeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let onArg = args[0] as! Bool
        do {
          try api.setExportMode(on: onArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setExportModeChannel.setMessageHandler(nil)
    }
    /// 开始导出(对齐旧原生 runExportFromURL):复用共享 stabilizer 逐帧
    /// 解码→process_frame→编码写文件,进度经 EngineEvents.onExportProgress 回报。
    /// 返回空串=成功;非空=错误信息(取消时返回「已取消」)。
    let startExportChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.PreviewApi.startExport\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startExportChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let reqArg = args[0] as! ExportRequest
        api.startExport(req: reqArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startExportChannel.setMessageHandler(nil)
    }
    /// 取消进行中的导出(置标志,导出循环下一帧自停)。
    let cancelExportChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runcam_gf.PreviewApi.cancelExport\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelExportChannel.setMessageHandler { _, reply in
        do {
          try api.cancelExport()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelExportChannel.setMessageHandler(nil)
    }
  }
}
