// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.runcam.runcam_gf

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * 视频/项目基础信息。对应 gyroflow_ffi.h 的 GyroflowVideoInfo。
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class VideoInfo (
  val width: Long? = null,
  val height: Long? = null,
  val outputWidth: Long? = null,
  val outputHeight: Long? = null,
  val fps: Double? = null,
  val durationS: Double? = null,
  val frameCount: Long? = null,
  val videoCodec: String? = null,
  val pixelFormat: String? = null,
  val audioCodec: String? = null,
  val audioSampleRate: Long? = null,
  val rotationDeg: Long? = null,
  val videoBitrate: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VideoInfo {
      val width = pigeonVar_list[0] as Long?
      val height = pigeonVar_list[1] as Long?
      val outputWidth = pigeonVar_list[2] as Long?
      val outputHeight = pigeonVar_list[3] as Long?
      val fps = pigeonVar_list[4] as Double?
      val durationS = pigeonVar_list[5] as Double?
      val frameCount = pigeonVar_list[6] as Long?
      val videoCodec = pigeonVar_list[7] as String?
      val pixelFormat = pigeonVar_list[8] as String?
      val audioCodec = pigeonVar_list[9] as String?
      val audioSampleRate = pigeonVar_list[10] as Long?
      val rotationDeg = pigeonVar_list[11] as Long?
      val videoBitrate = pigeonVar_list[12] as Long?
      return VideoInfo(width, height, outputWidth, outputHeight, fps, durationS, frameCount, videoCodec, pixelFormat, audioCodec, audioSampleRate, rotationDeg, videoBitrate)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      width,
      height,
      outputWidth,
      outputHeight,
      fps,
      durationS,
      frameCount,
      videoCodec,
      pixelFormat,
      audioCodec,
      audioSampleRate,
      rotationDeg,
      videoBitrate,
    )
  }
}

/**
 * recompute 后的只读输出(供 UI 显示最大修正角 / zoom% = 100/minFov)。
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class StabInfo (
  val maxAnglePitch: Double? = null,
  val maxAngleYaw: Double? = null,
  val maxAngleRoll: Double? = null,
  val minFov: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): StabInfo {
      val maxAnglePitch = pigeonVar_list[0] as Double?
      val maxAngleYaw = pigeonVar_list[1] as Double?
      val maxAngleRoll = pigeonVar_list[2] as Double?
      val minFov = pigeonVar_list[3] as Double?
      return StabInfo(maxAnglePitch, maxAngleYaw, maxAngleRoll, minFov)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      maxAnglePitch,
      maxAngleYaw,
      maxAngleRoll,
      minFov,
    )
  }
}

/**
 * 预览纹理信息(阶段1)。创建预览纹理后返回 textureId 与画面尺寸。
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PreviewInfo (
  val textureId: Long? = null,
  val width: Long? = null,
  val height: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PreviewInfo {
      val textureId = pigeonVar_list[0] as Long?
      val width = pigeonVar_list[1] as Long?
      val height = pigeonVar_list[2] as Long?
      return PreviewInfo(textureId, width, height)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      textureId,
      width,
      height,
    )
  }
}

/**
 * 导出请求(对齐旧原生 runExportFromURL 入参):源视频 + 输出位置 + 编码参数 + 输出尺寸。
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ExportRequest (
  val srcUri: String? = null,
  val outputUri: String? = null,
  val fileName: String? = null,
  val codecIndex: Long? = null,
  val bitrateMbps: Long? = null,
  val exportAudio: Boolean? = null,
  val width: Long? = null,
  val height: Long? = null,
  val trimStartUs: Long? = null,
  val trimEndUs: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ExportRequest {
      val srcUri = pigeonVar_list[0] as String?
      val outputUri = pigeonVar_list[1] as String?
      val fileName = pigeonVar_list[2] as String?
      val codecIndex = pigeonVar_list[3] as Long?
      val bitrateMbps = pigeonVar_list[4] as Long?
      val exportAudio = pigeonVar_list[5] as Boolean?
      val width = pigeonVar_list[6] as Long?
      val height = pigeonVar_list[7] as Long?
      val trimStartUs = pigeonVar_list[8] as Long?
      val trimEndUs = pigeonVar_list[9] as Long?
      return ExportRequest(srcUri, outputUri, fileName, codecIndex, bitrateMbps, exportAudio, width, height, trimStartUs, trimEndUs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      srcUri,
      outputUri,
      fileName,
      codecIndex,
      bitrateMbps,
      exportAudio,
      width,
      height,
      trimStartUs,
      trimEndUs,
    )
  }
}
private open class EngineApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VideoInfo.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          StabInfo.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PreviewInfo.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ExportRequest.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is VideoInfo -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is StabInfo -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is PreviewInfo -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is ExportRequest -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface EngineApi {
  fun createStabilizer()
  fun freeStabilizer()
  fun openVideo(uriOrPath: String, callback: (Result<VideoInfo>) -> Unit)
  fun setStabEnabled(enabled: Boolean)
  fun setSmoothingMethod(index: Long)
  fun setSmoothingParam(name: String, value: Double)
  /**
   * 对齐 gyroflow_set_horizon_lock 全 9 参。
   * (安卓 nativeSetHorizonLock 目前 2 参,impl 内补齐其余默认。)
   */
  fun setHorizonLock(lockPercent: Double, rollDeg: Double, lockPitch: Boolean, pitchDeg: Double, automaticLock: Boolean, turnThreshold: Double, turnSmoothingMs: Double, turnMultiplier: Double, tiltAccelLimit: Double)
  fun setAdaptiveZoom(windowSeconds: Double)
  fun setMaxZoom(percent: Double, iterations: Long)
  fun setZoomingMethod(index: Long)
  fun setLensCorrection(amount: Double)
  fun setFov(fov: Double)
  fun setFrameReadoutTime(ms: Double)
  fun setFrameReadoutDirection(dir: Long)
  fun setVideoSpeed(speed: Double, affectsSmoothing: Boolean, affectsZooming: Boolean, affectsZoomingLimit: Boolean)
  fun setAdditionalRotation(pitchDeg: Double, yawDeg: Double, rollDeg: Double)
  fun setBackgroundColor(r: Double, g: Double, b: Double, a: Double)
  fun setBackgroundMode(mode: Long)
  fun setShowSafeArea(show: Boolean)
  fun setShowDetectedFeatures(show: Boolean)
  fun setShowOpticalFlow(show: Boolean)
  fun setPreviewResolution(targetHeight: Long)
  fun setOutputSize(width: Long, height: Long)
  fun setOutputSizeExact(width: Long, height: Long)
  /**
   * 查询本机该编码格式硬件编码器的最大可导出分辨率 [maxW, maxH]。
   * 导出面板据此「按当前机型 + 编码格式」过滤输出大小预设(看得到的尺寸就一定能导出:
   * 三星支持 8K 就显示到 8K,华为只到 4K 就只显示到 4K)。codecIndex: 0=H.264 1=HEVC。
   * 仅只读查询能力,不创建编码器、不影响引擎/导出。查不到→返回编码标准规格上限兜底。
   */
  fun encoderMaxSize(codecIndex: Long): List<Long>
  fun setGyroOffset(offsetMs: Double)
  fun setImuLpf(hz: Double)
  fun setImuMedian(samples: Long)
  fun setImuRotation(pitchDeg: Double, rollDeg: Double, yawDeg: Double)
  fun setImuBias(x: Double, y: Double, z: Double)
  fun setImuOrientation(orientation: String)
  fun setIntegrationMethod(index: Long)
  fun setFrameOffset(frames: Long)
  fun lensSearch(query: String): String
  fun loadLens(uriOrIdOrJson: String): String
  fun getLensInfoFull(): String
  /** 当前已加载镜头库版本号(内置库/已安装更新包, 对应 gyroflow/lens_profiles 的 release 号)。 */
  fun getLensProfileDbVersion(): Long
  /** 安装下载的 profiles.cbor.gz 字节并热重载镜头库, 返回新版本号。失败抛异常。 */
  fun installLensProfiles(data: ByteArray): Long
  /**
   * 按当前已识别相机身份(camera_id)从内置库自动加载镜头档案。用于「相机身份在外挂
   * .gcsv 里、视频本身无 telemetry」的机型(如 RunCam6):加载 gcsv 后调用。
   * 返回 gyroflow_autoload_lens_for_camera 的 rc:0=已加载;-2=无可匹配/已有档案;-1=错。
   * (安卓 nativeLoadGyro 已在加载时内部自动配镜头,该方法在安卓为 no-op。)
   */
  fun autoloadLensForCamera(): Long
  fun loadGyro(uriOrPath: String, loadAllMetadata: Boolean): String
  fun folderAccessGranted(folderUrl: String)
  /**
   * 阻塞重算(放后台队列执行)+ 返回 max angles / min fov。
   * 完成后另经 EngineEvents.onRecomputeFinished 通知一次,便于 UI 统一刷新。
   */
  fun recomputeBlocking(callback: (Result<StabInfo>) -> Unit)
  fun getVideoMetadata(): String
  /**
   * 运动数据当前状态 JSON(供「输入」面板回显):
   * {"imu_orientation":"ZyX","has_quaternions":bool,"integration_method":int,
   *  "lpf":double,"median":int,"rotation":[p,r,y],"bias":[x,y,z]}
   * 安卓 nativeGetGyroInfo 全字段;iOS 用 get_imu_orientation + has_quaternions 拼核心字段。
   */
  fun getGyroInfo(): String
  fun gyroTimeline(count: Long): List<Double>
  fun quaternionTimeline(count: Long): List<Double>
  fun quatsAtTimestamp(timestampUs: Long): List<Double>
  fun getFovAtTimestamp(timestampUs: Long): Double
  fun autosyncStart(uriOrPath: String, initialOffsetMs: Double, searchSizeSec: Double, maxSyncPoints: Long, everyNthFrame: Long, timePerSyncpointSec: Double, ofMethod: Long, poseMethod: Long, offsetMethod: Long, calcInitialFast: Boolean, checkNegativeInitialOffset: Boolean, autoSyncPoints: Boolean)
  fun autosyncCancel()

  companion object {
    /** The codec used by EngineApi. */
    val codec: MessageCodec<Any?> by lazy {
      EngineApiPigeonCodec()
    }
    /** Sets up an instance of `EngineApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: EngineApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.createStabilizer$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.createStabilizer()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.freeStabilizer$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.freeStabilizer()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.openVideo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriOrPathArg = args[0] as String
            api.openVideo(uriOrPathArg) { result: Result<VideoInfo> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.setStabEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val enabledArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setStabEnabled(enabledArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.setSmoothingMethod$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val indexArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.setSmoothingMethod(indexArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.setSmoothingParam$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nameArg = args[0] as String
            val valueArg = args[1] as Double
            val wrapped: List<Any?> = try {
              api.setSmoothingParam(nameArg, valueArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.setHorizonLock$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val lockPercentArg = args[0] as Double
            val rollDegArg = args[1] as Double
            val lockPitchArg = args[2] as Boolean
            val pitchDegArg = args[3] as Double
            val automaticLockArg = args[4] as Boolean
            val turnThresholdArg = args[5] as Double
            val turnSmoothingMsArg = args[6] as Double
            val turnMultiplierArg = args[7] as Double
            val tiltAccelLimitArg = args[8] as Double
            val wrapped: List<Any?> = try {
              api.setHorizonLock(lockPercentArg, rollDegArg, lockPitchArg, pitchDegArg, automaticLockArg, turnThresholdArg, turnSmoothingMsArg, turnMultiplierArg, tiltAccelLimitArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.setAdaptiveZoom$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val windowSecondsArg = args[0] as Double
            val wrapped: List<Any?> = try {
              api.setAdaptiveZoom(windowSecondsArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.setMaxZoom$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val percentArg = args[0] as Double
            val iterationsArg = args[1] as Long
            val wrapped: List<Any?> = try {
              api.setMaxZoom(percentArg, iterationsArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.setZoomingMethod$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val indexArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.setZoomingMethod(indexArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.setLensCorrection$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val amountArg = args[0] as Double
            val wrapped: List<Any?> = try {
              api.setLensCorrection(amountArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.setFov$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val fovArg = args[0] as Double
            val wrapped: List<Any?> = try {
              api.setFov(fovArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.setFrameReadoutTime$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val msArg = args[0] as Double
            val wrapped: List<Any?> = try {
              api.setFrameReadoutTime(msArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.setFrameReadoutDirection$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val dirArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.setFrameReadoutDirection(dirArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.setVideoSpeed$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val speedArg = args[0] as Double
            val affectsSmoothingArg = args[1] as Boolean
            val affectsZoomingArg = args[2] as Boolean
            val affectsZoomingLimitArg = args[3] as Boolean
            val wrapped: List<Any?> = try {
              api.setVideoSpeed(speedArg, affectsSmoothingArg, affectsZoomingArg, affectsZoomingLimitArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.setAdditionalRotation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pitchDegArg = args[0] as Double
            val yawDegArg = args[1] as Double
            val rollDegArg = args[2] as Double
            val wrapped: List<Any?> = try {
              api.setAdditionalRotation(pitchDegArg, yawDegArg, rollDegArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.setBackgroundColor$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val rArg = args[0] as Double
            val gArg = args[1] as Double
            val bArg = args[2] as Double
            val aArg = args[3] as Double
            val wrapped: List<Any?> = try {
              api.setBackgroundColor(rArg, gArg, bArg, aArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.setBackgroundMode$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val modeArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.setBackgroundMode(modeArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.setShowSafeArea$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val showArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setShowSafeArea(showArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.setShowDetectedFeatures$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val showArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setShowDetectedFeatures(showArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.setShowOpticalFlow$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val showArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setShowOpticalFlow(showArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.setPreviewResolution$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val targetHeightArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.setPreviewResolution(targetHeightArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.setOutputSize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val widthArg = args[0] as Long
            val heightArg = args[1] as Long
            val wrapped: List<Any?> = try {
              api.setOutputSize(widthArg, heightArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.setOutputSizeExact$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val widthArg = args[0] as Long
            val heightArg = args[1] as Long
            val wrapped: List<Any?> = try {
              api.setOutputSizeExact(widthArg, heightArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.encoderMaxSize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val codecIndexArg = args[0] as Long
            val wrapped: List<Any?> = try {
              listOf(api.encoderMaxSize(codecIndexArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.setGyroOffset$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val offsetMsArg = args[0] as Double
            val wrapped: List<Any?> = try {
              api.setGyroOffset(offsetMsArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.setImuLpf$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val hzArg = args[0] as Double
            val wrapped: List<Any?> = try {
              api.setImuLpf(hzArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.setImuMedian$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val samplesArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.setImuMedian(samplesArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.setImuRotation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pitchDegArg = args[0] as Double
            val rollDegArg = args[1] as Double
            val yawDegArg = args[2] as Double
            val wrapped: List<Any?> = try {
              api.setImuRotation(pitchDegArg, rollDegArg, yawDegArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.setImuBias$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val xArg = args[0] as Double
            val yArg = args[1] as Double
            val zArg = args[2] as Double
            val wrapped: List<Any?> = try {
              api.setImuBias(xArg, yArg, zArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.setImuOrientation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val orientationArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.setImuOrientation(orientationArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.setIntegrationMethod$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val indexArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.setIntegrationMethod(indexArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.setFrameOffset$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val framesArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.setFrameOffset(framesArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.lensSearch$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val queryArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.lensSearch(queryArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.loadLens$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriOrIdOrJsonArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.loadLens(uriOrIdOrJsonArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.getLensInfoFull$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getLensInfoFull())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.getLensProfileDbVersion$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getLensProfileDbVersion())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.installLensProfiles$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val dataArg = args[0] as ByteArray
            val wrapped: List<Any?> = try {
              listOf(api.installLensProfiles(dataArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.autoloadLensForCamera$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.autoloadLensForCamera())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.loadGyro$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriOrPathArg = args[0] as String
            val loadAllMetadataArg = args[1] as Boolean
            val wrapped: List<Any?> = try {
              listOf(api.loadGyro(uriOrPathArg, loadAllMetadataArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.folderAccessGranted$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val folderUrlArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.folderAccessGranted(folderUrlArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.recomputeBlocking$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.recomputeBlocking{ result: Result<StabInfo> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.getVideoMetadata$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getVideoMetadata())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.getGyroInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getGyroInfo())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.gyroTimeline$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val countArg = args[0] as Long
            val wrapped: List<Any?> = try {
              listOf(api.gyroTimeline(countArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.quaternionTimeline$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val countArg = args[0] as Long
            val wrapped: List<Any?> = try {
              listOf(api.quaternionTimeline(countArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.quatsAtTimestamp$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val timestampUsArg = args[0] as Long
            val wrapped: List<Any?> = try {
              listOf(api.quatsAtTimestamp(timestampUsArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.getFovAtTimestamp$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val timestampUsArg = args[0] as Long
            val wrapped: List<Any?> = try {
              listOf(api.getFovAtTimestamp(timestampUsArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.autosyncStart$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriOrPathArg = args[0] as String
            val initialOffsetMsArg = args[1] as Double
            val searchSizeSecArg = args[2] as Double
            val maxSyncPointsArg = args[3] as Long
            val everyNthFrameArg = args[4] as Long
            val timePerSyncpointSecArg = args[5] as Double
            val ofMethodArg = args[6] as Long
            val poseMethodArg = args[7] as Long
            val offsetMethodArg = args[8] as Long
            val calcInitialFastArg = args[9] as Boolean
            val checkNegativeInitialOffsetArg = args[10] as Boolean
            val autoSyncPointsArg = args[11] as Boolean
            val wrapped: List<Any?> = try {
              api.autosyncStart(uriOrPathArg, initialOffsetMsArg, searchSizeSecArg, maxSyncPointsArg, everyNthFrameArg, timePerSyncpointSecArg, ofMethodArg, poseMethodArg, offsetMethodArg, calcInitialFastArg, checkNegativeInitialOffsetArg, autoSyncPointsArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.EngineApi.autosyncCancel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.autosyncCancel()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class EngineEvents(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by EngineEvents. */
    val codec: MessageCodec<Any?> by lazy {
      EngineApiPigeonCodec()
    }
  }
  /** recompute_blocking 在后台完成后,回主线程通知(刷 max angles / minFov)。 */
  fun onRecomputeFinished(infoArg: StabInfo, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.runcam_gf.EngineEvents.onRecomputeFinished$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(infoArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /** autosync 进度(ready/total 对齐官方 on_progress)。 */
  fun onAutosyncProgress(progressArg: Double, readyArg: Long, totalArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.runcam_gf.EngineEvents.onAutosyncProgress$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(progressArg, readyArg, totalArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /**
   * autosync 结束。medianOffsetMs 仅显示用;syncPoints 交错 [mid_ms, off_ms, ...]。
   * iOS 出参 / 安卓 JSON 在各端 impl 内归一成本回调。
   */
  fun onAutosyncFinished(medianOffsetMsArg: Double, syncPointsArg: List<Double>, okArg: Boolean, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.runcam_gf.EngineEvents.onAutosyncFinished$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(medianOffsetMsArg, syncPointsArg, okArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /** 导出进度(渲染线程回调,impl 内切回主线程再发)。 */
  fun onExportProgress(progressArg: Double, frameArg: Long, totalArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.runcam_gf.EngineEvents.onExportProgress$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(progressArg, frameArg, totalArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /** 播放推进:供 Flutter HUD 显示时间码 / zoom%(阶段 3 用)。 */
  fun onPlaybackTick(timestampUsArg: Long, fovArg: Double, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.runcam_gf.EngineEvents.onPlaybackTick$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(timestampUsArg, fovArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface PreviewApi {
  /**
   * 创建外接预览纹理。建解码器+CVPB 池+注册纹理,返回 textureId 与画面尺寸
   * (阶段1:iOS FlutterTexture / 安卓 SurfaceProducer)。
   */
  fun createPreviewTexture(uriOrPath: String): PreviewInfo
  fun disposePreviewTexture(textureId: Long)
  fun play()
  fun pause()
  fun seekTo(timestampUs: Long)
  /**
   * 暂停态按需重渲当前帧:参数改动后 recompute 完,主动刷新一次预览
   * (播放时渲染循环已连续刷新,无需调用)。
   */
  fun renderOnce()
  /**
   * 取并清零"自上次调用以来 copyPixelBuffer 被调次数"= Flutter 实际合成/上屏该
   * 纹理的帧数。每秒调一次即得真实合成 FPS(Dart 的 addTimingsCallback 只统计框架帧、
   * 看不到外部纹理合成,故须在原生侧计数)。
   */
  fun takeCompositedFrameCount(): Long
  /** 导出模式:开启后逐帧只渲输出供回读、不上屏(对齐 nativeSetExportMode)。 */
  fun setExportMode(on: Boolean)
  /**
   * 开始导出(对齐旧原生 runExportFromURL):复用共享 stabilizer 逐帧
   * 解码→process_frame→编码写文件,进度经 EngineEvents.onExportProgress 回报。
   * 返回空串=成功;非空=错误信息(取消时返回「已取消」)。
   */
  fun startExport(req: ExportRequest, callback: (Result<String>) -> Unit)
  /** 取消进行中的导出(置标志,导出循环下一帧自停)。 */
  fun cancelExport()

  companion object {
    /** The codec used by PreviewApi. */
    val codec: MessageCodec<Any?> by lazy {
      EngineApiPigeonCodec()
    }
    /** Sets up an instance of `PreviewApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PreviewApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.PreviewApi.createPreviewTexture$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriOrPathArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.createPreviewTexture(uriOrPathArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.PreviewApi.disposePreviewTexture$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textureIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.disposePreviewTexture(textureIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.PreviewApi.play$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.play()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.PreviewApi.pause$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.pause()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.PreviewApi.seekTo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val timestampUsArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.seekTo(timestampUsArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.PreviewApi.renderOnce$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.renderOnce()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.PreviewApi.takeCompositedFrameCount$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.takeCompositedFrameCount())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.PreviewApi.setExportMode$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val onArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setExportMode(onArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.PreviewApi.startExport$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val reqArg = args[0] as ExportRequest
            api.startExport(reqArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.runcam_gf.PreviewApi.cancelExport$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.cancelExport()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
